spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kakao:
  url: ${KAKAO_URL:https://dapi.kakao.com/v2/search/blog}
  keyPrefix: ${KAKAO_KEY_PREFIX:KakaoAK}
  apiKey: ${KAKAO_API_KEY:eb910bfed390a13b9d4b2b78b6f7c083}

naver:
  url: ${NAVAER_URL:https://openapi.naver.com/v1/search/blog.json}
  clientIdKey: ${CLIENT_ID_KEY:X-Naver-Client-Id}
  clientIdValue: ${CLIENT_ID_KEY:gEPKphu0l9J3YmayePQM}
  clientSecretKey: ${CLIENT_SECRET_KEY:X-Naver-Client-Secret}
  clientSecretValue: ${CLIENT_SECRET_KEY:zT9yEY3FFM}